const fs=require('fs');
let s=fs.readFileSync('dist/index.html','utf8');
const publisherPanel=s.match(/  <section class="panel"><div class="panel-head"><div><h2 id="companyTitle">.*?<\/section>/)[0].replaceAll('companyTitle','publisherTitle').replaceAll('Developers','Publishers').replaceAll('developers','publishers').replaceAll('devSubtitle','publisherSubtitle').replaceAll('companyRatingBtn','publisherRatingBtn').replaceAll('companyCountBtn','publisherCountBtn');
const modePanel='<section class="panel modes-panel"><div class="panel-head"><div><h2>Your game mode spread</h2><p class="panel-sub" id="modeSubtitle">IGDB game modes · each mode per game counts</p></div></div><div class="rating-layout"><div id="modeDonut" class="donut"><div class="donut-center" id="modeCenter"></div></div><div id="modeLegend" class="legend"></div></div></section>';
s=s.replace('  <div class="explore-pair span2">',publisherPanel+'\n  '+modePanel+'\n  <div class="explore-pair span2">');
s=s.replace('</style>','.modes-panel .legend-label{white-space:normal;overflow-wrap:anywhere}.modes-panel .swatch{flex-shrink:0}.modes-panel .legend-line{align-items:center}\n</style>');
s=s.replace("key==='genres'?genresFor(g):[g[key]]","key==='genres'?genresFor(g):['publishers','gameModes'].includes(key)?(g[key]||[]):[g[key]]");
s=s.replace("companySort='rating'","companySort='rating',publisherSort='rating'");
s=s.replace('games.map(g=>g.developerLogos||{})','games.map(g=>({...g.developerLogos,...g.publisherLogos}))');
const start=s.indexOf("    const companyGroups=groups(played,'developers')");
const end=s.indexOf("    for(const img",start);
let block=s.slice(start,end).replaceAll('companyGroups','publisherGroups').replaceAll('shownDevelopers','shownPublishers').replaceAll('companySort','publisherSort').replaceAll('companyMax','publisherMax').replaceAll("'developers'","'publishers'").replaceAll("'companyTitle'","'publisherTitle'").replaceAll("'devSubtitle'","'publisherSubtitle'").replaceAll('Developers','Publishers').replaceAll('Developer insights','Publisher insights').replaceAll('per developer','per publisher').replaceAll('data-kind="studio"','data-kind="publisher"');
s=s.slice(0,end)+block+s.slice(end);
const modeRender=`
    const modeGroups=groups(played,'gameModes').sort((a,b)=>b.count-a.count||a.name.localeCompare(b.name)),modeTotal=modeGroups.reduce((n,x)=>n+x.count,0),modeCoverage=played.filter(g=>g.gameModes?.length).length;
    let modePos=0;const modeSlices=modeGroups.map((x,i)=>{const start=modePos;modePos+=x.count/modeTotal*100;return colors[i%colors.length]+' '+start+'% '+modePos+'%'});
    $('modeDonut').style.background=modeTotal?'conic-gradient('+modeSlices.join(',')+')':'#353d4e';
    $('modeCenter').innerHTML=modeCoverage+'<small>games with modes</small>';
    $('modeSubtitle').textContent='IGDB · '+modeCoverage+'/'+played.length+' games · each mode per game counts';
    $('modeLegend').innerHTML=modeGroups.length?modeGroups.map((x,i)=>'<div class="legend-line"><span class="legend-label"><i class="swatch" style="background:'+colors[i%colors.length]+'"></i>'+esc(x.name)+'</span><span class="legend-count">'+x.count+'</span></div>').join(''):'<div class="empty">No game mode data yet.</div>';
`;
s=s.replace('    const sortedYears=',modeRender+'    const sortedYears=');
s=s.replaceAll("kind==='genre'?genresFor(g)","kind==='publisher'?(g.publishers||[]):kind==='genre'?genresFor(g)");
// Membership must be applied to publishers independently of the next ternary branch.
s=s.replaceAll("kind==='publisher'?(g.publishers||[]):kind==='genre'?genresFor(g).includes(key)","kind==='publisher'?(g.publishers||[]).includes(key):kind==='genre'?genresFor(g).includes(key)");
s=s.replaceAll("kind==='publisher'?(g.publishers||[]):kind==='genre'?genresFor(g).length","kind==='publisher'?(g.publishers||[]).length:kind==='genre'?genresFor(g).length");
s=s.replace("['developers','yearBars'","['developers','publishers','yearBars'");
const eventLine=s.split('\n').find(l=>l.includes("for(const [id,value] of [['companyRatingBtn'"));
s=s.replace(eventLine,eventLine+'\n'+eventLine.replaceAll('companyRatingBtn','publisherRatingBtn').replaceAll('companyCountBtn','publisherCountBtn').replaceAll('companySort','publisherSort'));
s=s.replaceAll('metadata:igdb-v1:', 'metadata:igdb-v2:');
s=s.replace("Array.isArray(data.genres)&&'plays' in data","Array.isArray(data.genres)&&Array.isArray(data.publishers)&&Array.isArray(data.gameModes)&&'plays' in data");
s=s.replace('genres:data.genres,plays:','genres:data.genres,publishers:data.publishers,publisherLogos:data.publisherLogos||{},gameModes:data.gameModes,plays:');
s=s.replace('genres:g.genres||[],plays:','genres:g.genres||[],publishers:g.publishers||[],publisherLogos:g.publisherLogos||{},gameModes:g.gameModes||[],plays:');
s=s.replace('genres:[],checked:false','genres:[],publishers:[],publisherLogos:{},gameModes:[],checked:false');
s=s.replace('Developer credits, logos, and genres come from IGDB','Developer and publisher credits, logos, genres, and game modes come from IGDB');
fs.writeFileSync('dist/index.html',s);
fs.writeFileSync('dist/server/page.js','export const page = '+JSON.stringify(s)+';\n');
let worker=fs.readFileSync('dist/server/index.js','utf8').replace('cache/igdb-v1','cache/igdb-v2');
fs.writeFileSync('dist/server/index.js',worker);
